### PR TITLE
Add cubed notebook for hourly climatology example using "map-reduce" method

### PR DESCRIPTION
**Pull request by tomwhite**
Follow on to #352

### CODE REVIEW

**Comment by dcherian** [comment]
The repr seems to be broken: https://flox--356.org.readthedocs.build/en/356/user-stories/climatology-hourly-cubed.html

**Comment by tomwhite** [comment]
The docs build may be failing because cubed 0.14.3 has only just been released (?). I get the same error when trying to create a conda env locally.

**Comment by tomwhite** [comment]
The HTML repr is now working: https://flox--356.org.readthedocs.build/en/356/user-stories/climatology-hourly-cubed.html

**Comment by dcherian** [comment]
Thanks! Can I suggest changing the color of that array in the repr? At a quick glance it's impossible to tell its not a dask array :)

**Pull request merged**
