### PR TITLE
Vectorized grouped (nan)quantile

### PR DESCRIPTION
**Pull request by dcherian**

### CODE REVIEW

**Comment by max-sixty** [comment]
Just saw this in the release notes — very nice!

Always feel free to ping numbagg if you want anything like this in there. (also nice to have it without numba though...)

**Comment by dcherian** [comment]
It's all vectorized so I'm not sure there's that much benefit. There might be some for the `lexsort` along an axis though

**Comment by max-sixty** [comment]
> It's all vectorized so I'm not sure there's that much benefit. There might be some for the `lexsort` along an axis though

Yes agree...

And numba is slower than numpy on sorting!

**Comment by dcherian** [comment]
> And numba is slower than numpy on sorting!

I have learned that intel engineers show up to optimize numpy's sorting with all kinds of SIMD tricks, so that's perhaps not so surprising: e.g. https://github.com/numpy/numpy/pull/25045

**Comment by max-sixty** [comment]
Nice!!

**Pull request merged**
